import React, {FunctionComponent} from 'react';
import {PreloadImagesWrapper} from './styles';
import n1Icon from '../../images/1.png';
import n10Icon from '../../images/10.png';
import n11Icon from '../../images/11.png';
import n12Icon from '../../images/12.png';
import n13Icon from '../../images/13.png';
import n14Icon from '../../images/14.png';
import n15Icon from '../../images/15.png';
import n16Icon from '../../images/16.png';
import n17Icon from '../../images/17.png';
import n18Icon from '../../images/18.png';
import n19Icon from '../../images/19.png';
import n2Icon from '../../images/2.png';
import n20Icon from '../../images/20.png';
import n21Icon from '../../images/21.png';
import n22Icon from '../../images/22.png';
import n23Icon from '../../images/23.png';
import n24Icon from '../../images/24.png';
import n3Icon from '../../images/3.png';
import n4Icon from '../../images/4.png';
import n5Icon from '../../images/5.png';
import n6Icon from '../../images/6.png';
import n7Icon from '../../images/7.png';
import n8Icon from '../../images/8.png';
import n9Icon from '../../images/9.png';
import addIcon from '../../images/add.png';
import axisIcon from '../../images/axis.png';
import blueprintIcon from '../../images/blueprint.png';
import cancelIcon from '../../images/cancel.png';
import checkedIcon from '../../images/checked.png';
import compassIcon from '../../images/compass.png';
import crosshairIcon from '../../images/crosshair.png';
import eyesIcon from '../../images/eyes.png';
import focusPointIcon from '../../images/focus-point.png';
import forbiddenIcon from '../../images/forbidden.png';
import calculusIcon from '../../images/calculus.png';
import imageIcon from '../../images/image.png';
import infinityIcon from '../../images/infinity.png';
import informationIcon from '../../images/information.png';
import markerIcon from '../../images/marker.png';
import mathsIcon from '../../images/maths.png';
import maximizeIcon from '../../images/maximize.png';
import minimizeIcon from '../../images/minimize.png';
import penIcon from '../../images/pen.png';
import pencilIcon from '../../images/pencil.png';
import pixelatedIcon from '../../images/pixelated.png';
import targetIcon from '../../images/target.png';
import textbookIcon from '../../images/textbook.png';
import zoomInIcon from '../../images/zoom-in.png';
import zoomOutIcon from '../../images/zoom-out.png';

export const PreloadImages: FunctionComponent = () => {
    return (
        <PreloadImagesWrapper>
            <img alt="" src={n1Icon} />
            <img alt="" src={n10Icon} />
            <img alt="" src={n11Icon} />
            <img alt="" src={n12Icon} />
            <img alt="" src={n13Icon} />
            <img alt="" src={n14Icon} />
            <img alt="" src={n15Icon} />
            <img alt="" src={n16Icon} />
            <img alt="" src={n17Icon} />
            <img alt="" src={n18Icon} />
            <img alt="" src={n19Icon} />
            <img alt="" src={n2Icon} />
            <img alt="" src={n20Icon} />
            <img alt="" src={n21Icon} />
            <img alt="" src={n22Icon} />
            <img alt="" src={n23Icon} />
            <img alt="" src={n24Icon} />
            <img alt="" src={n3Icon} />
            <img alt="" src={n4Icon} />
            <img alt="" src={n5Icon} />
            <img alt="" src={n6Icon} />
            <img alt="" src={n7Icon} />
            <img alt="" src={n8Icon} />
            <img alt="" src={n9Icon} />
            <img alt="" src={addIcon} />
            <img alt="" src={axisIcon} />
            <img alt="" src={blueprintIcon} />
            <img alt="" src={cancelIcon} />
            <img alt="" src={checkedIcon} />
            <img alt="" src={compassIcon} />
            <img alt="" src={crosshairIcon} />
            <img alt="" src={eyesIcon} />
            <img alt="" src={focusPointIcon} />
            <img alt="" src={forbiddenIcon} />
            <img alt="" src={calculusIcon} />
            <img alt="" src={imageIcon} />
            <img alt="" src={infinityIcon} />
            <img alt="" src={informationIcon} />
            <img alt="" src={markerIcon} />
            <img alt="" src={mathsIcon} />
            <img alt="" src={maximizeIcon} />
            <img alt="" src={minimizeIcon} />
            <img alt="" src={penIcon} />
            <img alt="" src={pencilIcon} />
            <img alt="" src={pixelatedIcon} />
            <img alt="" src={targetIcon} />
            <img alt="" src={textbookIcon} />
            <img alt="" src={zoomInIcon} />
            <img alt="" src={zoomOutIcon} />
        </PreloadImagesWrapper>
    );
};
